parameters:
  api_platform.ting.collection.pagination:
    enabled: '%api_platform.collection.pagination.enabled%'
    client_enabled: '%api_platform.collection.pagination.client_enabled%'
    client_items_per_pages: '%api_platform.collection.pagination.client_items_per_page%'
    items_per_page: '%api_platform.collection.pagination.items_per_page%'
    enabled_parameter_name: '%api_platform.collection.pagination.enabled_parameter_name%'
    items_per_page_parameter_name: '%api_platform.collection.pagination.items_per_page_parameter_name%'
    maximum_items_per_page: '%api_platform.collection.pagination.maximum_items_per_page%'
    page_parameter_name: '%api_platform.collection.pagination.page_parameter_name%'

  api_platform.ting.collection.order:
    order_parameter_name: '%api_platform.collection.order_parameter_name%'

services:
  api_platform.ting.metadata.resource.metadata_collection_factory:
    class: 'CCMBenchmark\Ting\ApiPlatform\Metadata\Resource\TingResourceMetadataCollectionFactory'
    decorates: 'api_platform.metadata.resource.metadata_collection_factory'
    decoration_priority: 40
    arguments:
        - '@api_platform.ting.repository_provider'
        - '@.inner'
  api_platform.ting.state.collection_provider:
    class: 'CCMBenchmark\Ting\ApiPlatform\CollectionDataProvider'
    arguments:
      - '@api_platform.ting.repository_provider'
      - '@request_stack'
      - '@api_platform.pagination_options'
      - '@api_platform.filter_locator'
    tags:
      - name: 'api_platform.state_provider'
        priority: -100
        key: 'CCMBenchmark\Ting\ApiPlatform\CollectionDataProvider'
      - name: 'api_platform.state_provider'
        priority: -100
        key: 'api_platform.ting.state.collection_provider'

  api_platform.ting.state.item_provider:
    class: 'CCMBenchmark\Ting\ApiPlatform\ItemDataProvider'
    arguments:
      - '@api_platform.ting.repository_provider'
    tags:
      - name: 'api_platform.state_provider'
        priority: -100
        key: 'CCMBenchmark\Ting\ApiPlatform\ItemDataProvider'
      - name: 'api_platform.state_provider'
        priority: -100
        key: 'api_platform.ting.item_data_provider'

  api_platform.ting.listener.view.write:
    class: 'CCMBenchmark\Ting\ApiPlatform\WriteListener'
    arguments: ['@api_platform.ting.repository_provider']
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.view', method: 'onKernelView', priority: 32 }

  api_platform.ting.repository_provider:
    class: 'CCMBenchmark\Ting\ApiPlatform\RepositoryProvider'
    arguments: ['@ting', '@ting.metadatarepository']
